# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0783476fa3c4fb41cc61455cd895269ae4e589fa291cf9bd2ac1ad0fe64aa413c8bb06918bfc26d263b71289092c4af63dbb76cddd7b634d5f28d1f5bd51ae43

test:
  secret_key_base: 4acae9647210f8d8d32d95d8fb95d073693c847bd17be848dd43a09927358d7b5b7b8cb3308056af7ef688eaddec327cb883daf4c6ac2834b026b98965e5e90d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
